import './style.css'

document.querySelector('#app').innerHTML = `
  <header class="nav-wrap"><nav class="nav container">
    <a class="logo" href="#home" aria-label="Nanco home"><span class="logo-mark">N</span><span>NANCO<span class="logo-dot">.</span></span></a>
    <div class="nav-links"><a href="#solutions">Solutions</a><a href="#security">Security</a><a href="#about">About us</a><a href="#contact">Contact</a></div>
    <div class="nav-actions"><a class="sign-in" href="#contact">Sign in <span>↗</span></a><a class="button button-small" href="#demo">Request a demo <span>↗</span></a></div>
    <button class="menu-toggle" aria-label="Open menu">☰</button>
  </nav></header>

  <main id="home">
    <section class="hero container"><div class="hero-copy"><p class="eyebrow"><span></span> The operating system for better estates</p><h1>Better estates,<br><em>by design.</em></h1><p class="hero-intro">Nanco brings people, places and the everyday work of running an estate into one calm, connected platform.</p><div class="hero-actions"><a class="button" href="#demo">See Nanco in action <span>↗</span></a><a class="text-link" href="#solutions">Explore the platform <span>↓</span></a></div></div><div class="hero-visual"><div class="visual-card card-main"><div class="card-top"><span class="mini-logo">N</span><span>Good morning, Ade</span><span class="status-dot"></span></div><div class="metric-label">Estate pulse <span>Today, 09:42</span></div><div class="metric"><strong>98.4%</strong><span class="positive">↑ 4.2%</span></div><div class="pulse"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="quick-grid"><div><b>24</b><small>Visitors today</small></div><div><b>12</b><small>Open incidents</small></div><div><b>₦2.4m</b><small>Collections</small></div></div></div><div class="float-card"><span class="float-icon">✓</span><div><b>Gate access approved</b><small>At Maplewood Gate · just now</small></div></div><div class="circle-stamp">SAFE<br><span>•</span><br>CONNECTED</div></div></section>

    <section class="marquee"><div class="container marquee-inner"><span>One platform. Every detail.</span><span>ESTATE MANAGEMENT</span><span>COMMUNITY LIVING</span><span>SMARTER SECURITY</span></div></section>

    <section class="section container" id="solutions"><div class="section-heading"><p class="eyebrow"><span></span> One platform, many perspectives</p><h2>Everything your estate needs<br><em>to move forward.</em></h2><p>From a visitor at the gate to a payment in the wallet, Nanco makes the moving parts of modern estate life feel simple.</p></div><div class="audience-grid"><article><span class="num">01</span><h3>For estate owners</h3><p>See the full picture, improve value and make decisions with confidence.</p><a href="#demo">Discover more <span>↗</span></a></article><article><span class="num">02</span><h3>For managers</h3><p>Run daily operations from one clear dashboard, without the busywork.</p><a href="#demo">Discover more <span>↗</span></a></article><article><span class="num">03</span><h3>For residents</h3><p>Enjoy a smoother, safer community experience, right from your phone.</p><a href="#demo">Discover more <span>↗</span></a></article><article><span class="num">04</span><h3>For security teams</h3><p>Give every guard the context and tools to keep people moving safely.</p><a href="#demo">Discover more <span>↗</span></a></article></div></section>

    <section class="dark-section" id="security"><div class="container security-layout"><div><p class="eyebrow light"><span></span> Security, with clarity</p><h2>Every entrance.<br><em>Every incident.</em><br>Under control.</h2><p class="dark-copy">Nanco gives your security team a shared, real-time view of what is happening across the estate — so they can respond faster and residents can feel at ease.</p><a class="button button-light" href="#demo">Explore security <span>↗</span></a></div><div class="security-panel"><div class="panel-header"><span>Security overview</span><span class="live"><i></i> Live</span></div><div class="map-placeholder"><span class="map-line line-one"></span><span class="map-line line-two"></span><span class="map-pin pin-one">G1</span><span class="map-pin pin-two">G2</span><span class="map-pin pin-three">G3</span><div class="map-label">MAPLEWOOD<br><small>Residential estate</small></div></div><div class="security-stats"><div><small>Gates online</small><b>04 / 04</b></div><div><small>Active guards</small><b>18</b></div><div><small>Incidents today</small><b class="green-text">02</b></div></div></div></div></section>

    <section class="section container modules"><div class="section-heading split"><div><p class="eyebrow"><span></span> The Nanco toolkit</p><h2>Designed for the<br><em>whole community.</em></h2></div><p>Powerful modules that work better together. Choose what your estate needs today, and grow from there.</p></div><div class="module-grid"><div><span>01</span><h3>Visitor access</h3><p>Pre-approve guests, deliveries and service providers.</p></div><div><span>02</span><h3>Residents</h3><p>Keep people, units and communications in sync.</p></div><div><span>03</span><h3>Guards & gates</h3><p>Equip teams with live context at every checkpoint.</p></div><div><span>04</span><h3>Utilities</h3><p>Track shared services and stay ahead of issues.</p></div><div><span>05</span><h3>Wallets & payments</h3><p>Make collections and community spending effortless.</p></div><div><span>06</span><h3>Incidents</h3><p>Log, assign and resolve with a clear audit trail.</p></div></div></section>

    <section class="cta container" id="demo"><div><p class="eyebrow light"><span></span> Ready when you are</p><h2>Make your estate<br><em>feel effortless.</em></h2><p>Let’s show you what a more connected community can look like.</p></div><a class="button button-light" href="mailto:hello@nanco.tech">Request a demo <span>↗</span></a></section>
  </main>
  <footer id="contact"><div class="container footer-grid"><div><a class="logo footer-logo" href="#home"><span class="logo-mark">N</span><span>NANCO<span class="logo-dot">.</span></span></a><p>Technology for places<br>people are proud to call home.</p></div><div><small>Explore</small><a href="#solutions">Solutions</a><a href="#security">Security</a><a href="#about">About us</a></div><div><small>Get in touch</small><a href="mailto:hello@nanco.tech">hello@nanco.tech</a><a href="#demo">Request a demo</a><a href="#contact">Sign in ↗</a></div></div><div class="container footer-bottom"><span>© 2025 Nanco Technologies</span><span>Lagos, Nigeria · Built for better living</span></div></footer>
`

document.querySelector('.menu-toggle').addEventListener('click', () => document.querySelector('.nav-links').classList.toggle('open'))
